apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    name: kafka
spec:
  ports:
  - port: 9092
    name: server
  selector:
    app: kafka
    name: kafka
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  minAvailable: 1
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk-cs:2181
        name: kafka
        image: hashmapinc/kafka:1.0
        ports:
        - containerPort: 9092
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: kafkadir
  volumeClaimTemplates:
  - metadata:
      name: kafkadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: ebs-gp2
