kind: Service
apiVersion: v1
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  type: LoadBalancer
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 9191
      targetPort: 9191
      name: nifi
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: nifi
spec:
  selector:
    matchLabels:
      app: nifi
  serviceName: nifi
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: hashmapinc/nifi:1.0
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9091
          name: nifi
        volumeMounts:
        - mountPath: /opt/nifi/nifi-1.4.0/flowfile_repository
          name: nifi-flowfile-repo-dir
        - mountPath: /opt/nifi/nifi-1.4.0/database_repository
          name: nifi-db-repo-dir
        - mountPath: /opt/nifi/nifi-1.4.0/content_repository
          name: nifi-content-repo-dir
        - mountPath: /opt/nifi/nifi-1.3.0/provenance_repository
          name: nifi-provenance-repo-dir
        - mountPath: /opt/nifi/nifi-1.3.0/logs
          name: nifi-log-dir
  volumeClaimTemplates:
  - metadata:
      name: nifi-flowfile-repo-dir 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: ebs-gp2
  - metadata:
      name: nifi-db-repo-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: ebs-gp2
  - metadata:
      name: nifi-content-repo-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: ebs-gp2
  - metadata:
      name: nifi-provenance-repo-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: ebs-gp2
  - metadata:
      name: nifi-log-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: ebs-gp2
